eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
okta:
  oauth2:
    issuer: https://dev-38798739.okta.com/oauth2/default
    audience: api://default
